/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppCafe;

/**
 *
 * @author Andika Risky Septiawan
 */

import java.sql.*;
import javax.swing.*;
public class Login extends javax.swing.JFrame {
    // deklarasikan  terlebih dahulu untuk menghubungkan ke database
    Connection conn;
    Statement stm;
    ResultSet rs;
    PreparedStatement pst;
    // deklarasikan sql menggunakan tipe data string untuk menyimpan command sql
    String sql;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        showMessageBox();
        tbPassword.setEchoChar('\u25cf');
        // pemanggilan fungsi koneksi database yang sudah dibuat pada config.java
        Koneksi DB = new Koneksi();
        DB.config();
        conn = DB.conn;
        stm = DB.stm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbEmail = new javax.swing.JTextPane();
        bLogin = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        tbPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Snap ITC", 2, 24)); // NOI18N
        jLabel1.setText("Login Cafe Bisa Ngopi");

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setText("Username");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel3.setText("Password");

        tbEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(tbEmail);

        bLogin.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        bLogin.setText("Login");
        bLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLoginMouseClicked(evt);
            }
        });
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        btClear.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        btClear.setText("Clear");
        btClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btClearMouseClicked(evt);
            }
        });
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });

        tbPassword.setText("asasas");
        tbPassword.setDragEnabled(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(bLogin)
                                    .addGap(18, 18, 18)
                                    .addComponent(btClear)
                                    .addGap(34, 34, 34))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tbPassword)))))
                    .addComponent(jLabel1))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLogin)
                    .addComponent(btClear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bLoginActionPerformed

    private void bLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLoginMouseClicked
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_bLoginMouseClicked

    private void btClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btClearMouseClicked
        // TODO add your handling code here:
        tbEmail.setText("");
        tbPassword.setText("");
    }//GEN-LAST:event_btClearMouseClicked

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JButton btClear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane tbEmail;
    private javax.swing.JPasswordField tbPassword;
    // End of variables declaration//GEN-END:variables

    private void login() {
        //Membuat koneksi ke database
        try {
            // Membuat Command/perintah sql untuk mengambil username dan password 
            // dari database
            sql = "SELECT * FROM user WHERE username='"+tbEmail.getText()+
                    "' AND password='"+tbPassword.getText()+"'";
            // Meng-eksekusi Command/perintah sql ynag dimasukkan
            rs = stm.executeQuery(sql);
            // Untuk mengetahui username dan password yang dimasukkan benar atau salah
            if (rs.next()) {
                if (tbEmail.getText().equals(rs.getString("username")) && 
                        (tbPassword.getText().equals(rs.getString("password")))) {
                    // Jika benar/berhasil masuk maka akan menentukan role_id
                    if (rs.getString("role_id").equals("0")) {
                        login_log(rs.getString("id_user"));
                        // Jika role_id = 0 maka masuk ke tampilan Admin
                        RegisterAdmin RA = new RegisterAdmin();
                        RA.setVisible(true);
                        // Jika form Pendaftaran akun tampil maka form login tertutup
                        this.setVisible(false);
                        
                    } else if (rs.getString("role_id").equals("1")) {
                        login_log(rs.getString("id_user"));
                        // Jika role_id = 1 maka masuk ke tampilan Manajer
                        MenuManajer MM = new MenuManajer();
                        MM.setVisible(true);
                        // Jika form Menu tampil maka form login tertutup
                        this.setVisible(false);
                        
                    } else if (rs.getString("role_id").equals("2")) {
                        login_log(rs.getString("id_user"));
                        // Jika role_id = 2 maka masuk ke tampilan Kasir
                        TransaksiKasir TK = new TransaksiKasir();
                        TK.namaid(rs.getString("nama_user"), rs.getString("id_user"));
                        TK.setVisible(true);
                        // Jika form Kasir tampil maka form login tertutup
                        this.setVisible(false);
                    }
                }
            } else {
                // Jika username atau password yang dimasukkan salah maka muncul message box
                JOptionPane.showMessageDialog(null, "Username atau Password salah");
            }
        } catch (Exception e) {
            // Jika koneksi ke database gagal akan menampilkan pesan error
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void login_log(String id_user) {
        try {
            sql = "INSERT INTO log_aktivitas VALUES (NULL, '" + id_user +"', current_timestamp(), 'Login')";
            pst = conn.prepareStatement(sql);
            pst.execute();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    private void showMessageBox() {
        JOptionPane.showMessageDialog(null, "Program ini dibuat oleh \n"
                + "Andika Risky Septiawan | https://github.com/andikariskys");
    }
}
