/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppCafe;

/**
 *
 * @author Andika Risky Septiawan
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class MenuManajer extends javax.swing.JFrame {
    String sql;
    Connection conn;
    Statement stmt;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form Menu
     */
    public MenuManajer() throws SQLException {
        initComponents();
        
        Koneksi DB = new Koneksi();
        DB.config();
        conn = DB.conn;
        stmt = DB.stm;
        
        load_table();
        bersihkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSimpanEdit = new javax.swing.JButton();
        btnTambahMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbIdMenu = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbNamaMenu = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbHargaMenu = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDaftarMenu = new javax.swing.JTable();
        btnHapusMenu = new javax.swing.JButton();
        btnClearMenu = new javax.swing.JButton();
        btnLaporanPendapatan = new javax.swing.JButton();
        btnLogAktivitas = new javax.swing.JButton();
        btnCatatanTransaksi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Snap ITC", 2, 24)); // NOI18N
        jLabel1.setText("Daftar Menu Cafe Bisa Ngopi");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel3.setText("Id Menu");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel4.setText("Nama Menu");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setText("Harga");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        btnSimpanEdit.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        btnSimpanEdit.setText("Simpan Edit Menu");
        btnSimpanEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanEditMouseClicked(evt);
            }
        });

        btnTambahMenu.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        btnTambahMenu.setText("Tambah Menu");
        btnTambahMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMenuMouseClicked(evt);
            }
        });
        btnTambahMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahMenuActionPerformed(evt);
            }
        });

        tbIdMenu.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tbIdMenu.setEnabled(false);
        jScrollPane1.setViewportView(tbIdMenu);

        tbNamaMenu.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(tbNamaMenu);

        tbHargaMenu.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(tbHargaMenu);

        tblDaftarMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDaftarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDaftarMenuMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblDaftarMenu);

        btnHapusMenu.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        btnHapusMenu.setText("Hapus Menu");
        btnHapusMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMenuMouseClicked(evt);
            }
        });

        btnClearMenu.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        btnClearMenu.setText("Bersihkan");
        btnClearMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMenuMouseClicked(evt);
            }
        });

        btnLaporanPendapatan.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        btnLaporanPendapatan.setText("Laporan Pendapatan");
        btnLaporanPendapatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaporanPendapatanMouseClicked(evt);
            }
        });

        btnLogAktivitas.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        btnLogAktivitas.setText("Log Aktivitas");
        btnLogAktivitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogAktivitasMouseClicked(evt);
            }
        });

        btnCatatanTransaksi.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        btnCatatanTransaksi.setText("Catatan Transaksi");
        btnCatatanTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCatatanTransaksiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(170, 170, 170)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnSimpanEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTambahMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHapusMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnClearMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnLaporanPendapatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCatatanTransaksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogAktivitas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLaporanPendapatan)
                    .addComponent(btnLogAktivitas)
                    .addComponent(btnCatatanTransaksi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTambahMenu)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSimpanEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapusMenu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClearMenu)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void tblDaftarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDaftarMenuMouseClicked
        // TODO add your handling code here:
        //Menampilkan data kedalam form pengisian:
        int baris = tblDaftarMenu.rowAtPoint(evt.getPoint());
        
        // deklarasikan value yang di-klik kedalam variabel terlebih dahulu
        String id_menu = tblDaftarMenu.getValueAt(baris, 1).toString();
        String nama_menu = tblDaftarMenu.getValueAt(baris, 2).toString();
        String harga_menu = tblDaftarMenu.getValueAt(baris, 3).toString();
        
        // masukkan value dari variabel kedalam textbox
        tbIdMenu.setText(id_menu);
        tbNamaMenu.setText(nama_menu);
        tbHargaMenu.setText(harga_menu);
    }//GEN-LAST:event_tblDaftarMenuMouseClicked

    private void btnClearMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMenuMouseClicked
        // TODO add your handling code here:
        bersihkan();
    }//GEN-LAST:event_btnClearMenuMouseClicked

    private void btnTambahMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMenuMouseClicked
        // TODO add your handling code here:
        try {
            sql = "INSERT INTO menu VALUES (NULL, '" + tbNamaMenu.getText() + "', '" +
                    tbHargaMenu.getText() + "')";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Simpan Data Berhasil");
            load_table();
            bersihkan();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnTambahMenuMouseClicked

    private void btnTambahMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahMenuActionPerformed

    private void btnSimpanEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanEditMouseClicked
        // TODO add your handling code here:
        try {
            sql = "UPDATE menu SET nama_menu = '" + tbNamaMenu.getText() +"', harga_menu = '" + 
                    tbHargaMenu.getText() + "' WHERE id_menu = " + tbIdMenu.getText();
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Perubahan Data berhasil disimpan");
            load_table();
            bersihkan();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSimpanEditMouseClicked

    private void btnHapusMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMenuMouseClicked
        // TODO add your handling code here:
        try {
            sql = "DELETE FROM menu WHERE id_menu = " + tbIdMenu.getText();
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            load_table();
            bersihkan();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHapusMenuMouseClicked

    private void btnLaporanPendapatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanPendapatanMouseClicked
        // halaman menumanajer
        try {
            // TODO add your handling code here:
            LaporanPendapatanManajer pendapatan = new LaporanPendapatanManajer();
            pendapatan.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
        }
        
    }//GEN-LAST:event_btnLaporanPendapatanMouseClicked

    private void btnLogAktivitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogAktivitasMouseClicked
        // halaman menumanajer
        try {
            // TODO add your handling code here:
            LogAktivitasAdminManajer aktivitas = new LogAktivitasAdminManajer();
            aktivitas.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_btnLogAktivitasMouseClicked

    private void btnCatatanTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCatatanTransaksiMouseClicked
        // halaman MenuManajer
        try {
            // TODO add your handling code here:
            CatatanTransaksiManajer manajer = new CatatanTransaksiManajer();
            manajer.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_btnCatatanTransaksiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuManajer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuManajer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuManajer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuManajer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MenuManajer().setVisible(true);
                } catch (SQLException e) {
                    
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCatatanTransaksi;
    private javax.swing.JButton btnClearMenu;
    private javax.swing.JButton btnHapusMenu;
    private javax.swing.JButton btnLaporanPendapatan;
    private javax.swing.JButton btnLogAktivitas;
    private javax.swing.JButton btnSimpanEdit;
    private javax.swing.JButton btnTambahMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextPane tbHargaMenu;
    private javax.swing.JTextPane tbIdMenu;
    private javax.swing.JTextPane tbNamaMenu;
    private javax.swing.JTable tblDaftarMenu;
    // End of variables declaration//GEN-END:variables

    private void load_table() throws SQLException {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Id Menu");
        model.addColumn("Nama Menu");
        model.addColumn("Harga Menu");
                
        try {
            sql = "SELECT * FROM menu";
            rs = stmt.executeQuery(sql);
            int no = 1;
            while (rs.next()) {
                model.addRow(new Object[] {no++, rs.getInt("id_menu"), rs.getString("nama_menu"), 
                    rs.getInt("harga_menu")});
            }
        } catch (SQLException e) {
        }
        
        tblDaftarMenu.setModel(model);
    }

    private void bersihkan() {
        tbIdMenu.setText("");
        tbNamaMenu.setText("");
        tbHargaMenu.setText("");
    }
}
