/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppCafe;

/**
 *
 * @author Andika Risky Septiawan
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class RegisterAdmin extends javax.swing.JFrame {
    String sql;
    Connection conn;
    Statement stmt;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form Register
     */
    public RegisterAdmin() throws SQLException {
        initComponents();
        
        Koneksi DB = new Koneksi();
        DB.config();
        conn = DB.conn;
        stmt = DB.stm;
        
        load_table();
        bersihkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnGrpRole = new javax.swing.ButtonGroup();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPasswordReg = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        btnSimpanUser = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        radioAdmin = new javax.swing.JRadioButton();
        radioManajer = new javax.swing.JRadioButton();
        radioKasir = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnHapusUser = new javax.swing.JButton();
        btnEdituser = new javax.swing.JButton();
        btnClearUser = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbUsernameReg = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbNameReg = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbIdUser = new javax.swing.JTextPane();
        btnLogAktifitas = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jButton1.setText("jButton1");

        jScrollPane8.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Snap ITC", 2, 24)); // NOI18N
        jLabel1.setText("Register Cafe Bisa Ngopi");

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setText("ID User");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Snap ITC", 2, 24)); // NOI18N
        jLabel4.setText("(Admin Mode)");

        tbPasswordReg.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(tbPasswordReg);

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tblUser.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblUserAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblUser);

        btnSimpanUser.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        btnSimpanUser.setText("Simpan");
        btnSimpanUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanUserMouseClicked(evt);
            }
        });
        btnSimpanUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanUserActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel5.setText("Username");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        btnGrpRole.add(radioAdmin);
        radioAdmin.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        radioAdmin.setText("Admin");

        btnGrpRole.add(radioManajer);
        radioManajer.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        radioManajer.setText("Manajer");

        btnGrpRole.add(radioKasir);
        radioKasir.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        radioKasir.setText("Kasir");

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setText("Name");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel7.setText("Role User");

        btnHapusUser.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        btnHapusUser.setText("Hapus");
        btnHapusUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusUserMouseClicked(evt);
            }
        });
        btnHapusUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusUserActionPerformed(evt);
            }
        });

        btnEdituser.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        btnEdituser.setText("Simpan edit");
        btnEdituser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEdituserMouseClicked(evt);
            }
        });
        btnEdituser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdituserActionPerformed(evt);
            }
        });

        btnClearUser.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        btnClearUser.setText("Bersihkan");
        btnClearUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearUserMouseClicked(evt);
            }
        });
        btnClearUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearUserActionPerformed(evt);
            }
        });

        tbUsernameReg.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(tbUsernameReg);

        tbNameReg.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jScrollPane6.setViewportView(tbNameReg);

        tbIdUser.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tbIdUser.setEnabled(false);
        jScrollPane7.setViewportView(tbIdUser);

        btnLogAktifitas.setText("Log Aktifitas");
        btnLogAktifitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogAktifitasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(radioAdmin)
                                            .addGap(18, 18, 18)
                                            .addComponent(radioManajer)
                                            .addGap(18, 18, 18)
                                            .addComponent(radioKasir))
                                        .addComponent(jScrollPane6)))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEdituser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHapusUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClearUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(485, 485, 485)
                            .addComponent(btnSimpanUser, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnLogAktifitas)))
                .addGap(0, 137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnLogAktifitas)
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSimpanUser)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(26, 26, 26)
                            .addComponent(jLabel5))
                        .addComponent(btnEdituser))
                    .addComponent(btnHapusUser)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearUser))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAdmin)
                    .addComponent(radioManajer)
                    .addComponent(radioKasir)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void tblUserAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblUserAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblUserAncestorAdded

    private void tblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMouseClicked
        // TODO add your handling code here:
        //Menampilkan data kedalam form pengisian:
        int baris = tblUser.rowAtPoint(evt.getPoint());
        
        String id_user = tblUser.getValueAt(baris, 1).toString();
        String nama_user = tblUser.getValueAt(baris, 2).toString();
        String username_user = tblUser.getValueAt(baris, 3).toString();
        String password = tblUser.getValueAt(baris, 4).toString();
        
        tbIdUser.setText(id_user);
        tbNameReg.setText(nama_user);
        tbUsernameReg.setText(username_user);
        tbPasswordReg.setText(password);
        
        if (tblUser.getValueAt(baris, 5).toString().equals("0")) {
            radioAdmin.setSelected(true);
        } else if (tblUser.getValueAt(baris, 5).toString().equals("1")) {
            radioManajer.setSelected(true);
        } else if (tblUser.getValueAt(baris, 5).toString().equals("2")) {
            radioKasir.setSelected(true);
        }
    }//GEN-LAST:event_tblUserMouseClicked

    private void btnSimpanUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanUserActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btnHapusUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusUserActionPerformed

    private void btnEdituserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdituserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEdituserActionPerformed

    private void btnClearUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearUserActionPerformed

    private void btnClearUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearUserMouseClicked
        // TODO add your handling code here:
        bersihkan();
    }//GEN-LAST:event_btnClearUserMouseClicked

    private void btnSimpanUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanUserMouseClicked
        // TODO add your handling code here:
        String nama = tbNameReg.getText();
        String username = tbUsernameReg.getText();
        String password = tbPasswordReg.getText();
        
        String role_id = "null";
                if (radioAdmin.isSelected()) {
                    role_id = "0";
                } else if(radioManajer.isSelected()) {
                    role_id = "1";
                } else if(radioKasir.isSelected()) {
                    role_id = "2";
                }
                
        if (nama.equals("")) {
            JOptionPane.showMessageDialog(null, "Masukkan nama User terlebih dahulu");
        } else if (username.equals("")){
            JOptionPane.showMessageDialog(null, "Masukkan username User terlebih dahulu");
        } else if (password.equals("")) {
            JOptionPane.showMessageDialog(null, "Masukkan password User terlebih dahulu");
        } else if (role_id.equals("null")) {
            JOptionPane.showMessageDialog(null, "Pilih jabatan User terlebih dahulu");
        } else {
            try {
                sql = "INSERT INTO user VALUES (NULL, '" + nama + "', '" + username + "', '" + 
                        password + "', '" + role_id + "')";
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                load_table();
                bersihkan();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnSimpanUserMouseClicked

    private void btnEdituserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEdituserMouseClicked
        // TODO add your handling code here:
        String idUser = tbIdUser.getText();
        if (idUser.equals("")) {
            JOptionPane.showMessageDialog(null, "Pilih User yang ingin diubah");
        } else {
            try {
                int role_id = 0;
                if (radioAdmin.isSelected()) {
                    role_id = 0;
                } else if(radioManajer.isSelected()) {
                    role_id = 1;
                } else if(radioKasir.isSelected()) {
                    role_id = 2;
                }

                sql = "UPDATE user SET nama_user = '" + tbNameReg.getText() + "', username = '" + 
                        tbUsernameReg.getText() + "', password = '" + tbPasswordReg.getText() + 
                        "', role_id = '" + role_id + "' WHERE id_user =" + idUser;
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                load_table();
                bersihkan();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnEdituserMouseClicked

    private void btnHapusUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusUserMouseClicked
        // TODO add your handling code here:
        String idUser = tbIdUser.getText();
        
        if (idUser.equals("")) {
            JOptionPane.showMessageDialog(null, "Pilih User yang ingin dihapus terlebih dahulu");
        } else {
            try {
                sql = "DELETE FROM user WHERE id_user =" + idUser;
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                load_table();
                bersihkan();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnHapusUserMouseClicked

    private void btnLogAktifitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogAktifitasMouseClicked
        try {
            // TODO add your handling code here:
            LogAktivitasAdminManajer aktifitas = new LogAktivitasAdminManajer();
            aktifitas.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_btnLogAktifitasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RegisterAdmin().setVisible(true);
                } catch (SQLException e) {
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearUser;
    private javax.swing.JButton btnEdituser;
    private javax.swing.ButtonGroup btnGrpRole;
    private javax.swing.JButton btnHapusUser;
    private javax.swing.JButton btnLogAktifitas;
    private javax.swing.JButton btnSimpanUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JRadioButton radioAdmin;
    private javax.swing.JRadioButton radioKasir;
    private javax.swing.JRadioButton radioManajer;
    private javax.swing.JTextPane tbIdUser;
    private javax.swing.JTextPane tbNameReg;
    private javax.swing.JTextPane tbPasswordReg;
    private javax.swing.JTextPane tbUsernameReg;
    private javax.swing.JTable tblUser;
    // End of variables declaration//GEN-END:variables

    private void load_table() throws SQLException {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Id USer");
        model.addColumn("Nama User");
        model.addColumn("Username");
        model.addColumn("Password");
        model.addColumn("Role Id User");
        
        try {
            sql = "SELECT * FROM user";
            rs = stmt.executeQuery(sql);
            int no = 1;
            while (rs.next()) {                
                model.addRow(new Object[] {no++, rs.getInt("id_user"), 
                    rs.getString("nama_user"), rs.getString("username"), 
                    rs.getString("password"), rs.getInt("role_id")});
            }
        } catch (Exception e) {
        }
        
        tblUser.setModel(model);
    }

    private void bersihkan() {
        tbIdUser.setText("");
        tbNameReg.setText("");
        tbUsernameReg.setText("");
        tbPasswordReg.setText("");
        btnGrpRole.clearSelection();
    }
}
